import AppFooter from '@/components/app.footer';
import AppHeader from '@/components/app.header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Financial Report',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppHeader />
				{children}
				<AppFooter />
			</body>
		</html>
	);
}
