import SideNav from '@/components/app.sidenav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Financial Report',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
			</head>
			<body className='w-screen h-screen p-0 m-0 bg-light-gray'>
				<div className='h-full w-full grid grid-cols-14'>
					<SideNav />
					<div className='col-span-12 w-full h-full'>{children}</div>
				</div>
			</body>
		</html>
	);
}
